[2025-07-11T16:00:05.172+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-11T16:00:05.194+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: employee_ingestion_dag.validate_data scheduled__2025-07-11T15:59:00+00:00 [queued]>
[2025-07-11T16:00:05.204+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: employee_ingestion_dag.validate_data scheduled__2025-07-11T15:59:00+00:00 [queued]>
[2025-07-11T16:00:05.204+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-11T16:00:05.215+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): validate_data> on 2025-07-11 15:59:00+00:00
[2025-07-11T16:00:05.221+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=643) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-11T16:00:05.222+0000] {standard_task_runner.py:72} INFO - Started process 644 to run task
[2025-07-11T16:00:05.223+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'employee_ingestion_dag', 'validate_data', 'scheduled__2025-07-11T15:59:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_pipeline.py', '--cfg-path', '/tmp/tmpi57jgf3f']
[2025-07-11T16:00:05.224+0000] {standard_task_runner.py:105} INFO - Job 98: Subtask validate_data
[2025-07-11T16:00:05.291+0000] {task_command.py:467} INFO - Running <TaskInstance: employee_ingestion_dag.validate_data scheduled__2025-07-11T15:59:00+00:00 [running]> on host 5a07e0ddeb4c
[2025-07-11T16:00:05.392+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='employee_ingestion_dag' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-11T15:59:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-11T15:59:00+00:00'
[2025-07-11T16:00:05.394+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-11T16:00:08.053+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/great_expectations/data_context/data_context/serializable_data_context.py:225: UserWarning: Warning. An existing `great_expectations.yml` was found here: /opt/airflow/gx.
    - No action was taken.
  warnings.warn(message)

[2025-07-11T16:00:08.054+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/great_expectations/data_context/data_context/serializable_data_context.py:233: UserWarning: Warning. An existing `config_variables.yml` was found here: /opt/airflow/gx/uncommitted.
    - No action was taken.
  warnings.warn(message)

[2025-07-11T16:00:08.090+0000] {file_data_context.py:222} INFO - FileDataContext loading fluent config
[2025-07-11T16:00:08.104+0000] {config.py:187} INFO - Loading 'datasources' ->
[{'assets': [...], 'name': 'employee_datasource', 'type': 'pandas'}]
[2025-07-11T16:00:08.105+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-11T16:00:08.236+0000] {abstract_data_context.py:5516} INFO - Loaded 'employee_datasource' from fluent config
[2025-07-11T16:00:08.278+0000] {file_data_context.py:174} INFO - Saving 1 Fluent Datasources to /opt/airflow/great_expectations/great_expectations.yml
[2025-07-11T16:00:08.279+0000] {fluent_base_model.py:276} INFO - PandasDatasource.dict() - missing `config_provider`, skipping config substitution
[2025-07-11T16:00:08.302+0000] {file_data_context.py:174} INFO - Saving 1 Fluent Datasources to /opt/airflow/great_expectations/great_expectations.yml
[2025-07-11T16:00:08.304+0000] {fluent_base_model.py:276} INFO - CSVAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-11T16:00:08.304+0000] {fluent_base_model.py:276} INFO - PandasDatasource.dict() - missing `config_provider`, skipping config substitution
[2025-07-11T16:00:08.378+0000] {validator.py:1461} INFO - 	14 expectation(s) included in expectation_suite.
[2025-07-11T16:00:09.013+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   0%|          | 0/40 [00:00<?, ?it/s]
[2025-07-11T16:00:09.014+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   0%|          | 0/40 [00:00<?, ?it/s]
[2025-07-11T16:00:09.016+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   5%|5         | 2/40 [00:00<00:00, 1101.16it/s]
[2025-07-11T16:00:09.385+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   5%|5         | 2/40 [00:00<00:07,  5.40it/s]  
[2025-07-11T16:00:09.386+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   5%|5         | 2/40 [00:00<00:07,  5.40it/s]
[2025-07-11T16:00:09.387+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   8%|7         | 3/40 [00:00<00:06,  5.40it/s]
[2025-07-11T16:00:09.751+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   8%|7         | 3/40 [00:00<00:09,  3.84it/s]
[2025-07-11T16:00:09.752+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   8%|7         | 3/40 [00:00<00:09,  3.84it/s]
[2025-07-11T16:00:10.085+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   8%|7         | 3/40 [00:01<00:09,  3.84it/s]
[2025-07-11T16:00:10.418+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   8%|7         | 3/40 [00:01<00:09,  3.84it/s]
[2025-07-11T16:00:10.746+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   8%|7         | 3/40 [00:01<00:09,  3.84it/s]
[2025-07-11T16:00:11.070+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   8%|7         | 3/40 [00:02<00:09,  3.84it/s]
[2025-07-11T16:00:11.407+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   8%|7         | 3/40 [00:02<00:09,  3.84it/s]
[2025-07-11T16:00:11.747+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   8%|7         | 3/40 [00:02<00:09,  3.84it/s]
[2025-07-11T16:00:11.768+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:  38%|###7      | 15/40 [00:02<00:04,  5.57it/s]
[2025-07-11T16:00:11.769+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:  38%|###7      | 15/40 [00:02<00:04,  5.57it/s]
[2025-07-11T16:00:12.020+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:  38%|###7      | 15/40 [00:03<00:04,  5.57it/s]
[2025-07-11T16:00:12.052+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:  90%|######### | 36/40 [00:03<00:00, 15.27it/s]
[2025-07-11T16:00:12.053+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:  90%|######### | 36/40 [00:03<00:00, 15.27it/s]
[2025-07-11T16:00:12.185+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:  90%|######### | 36/40 [00:03<00:00, 15.27it/s]
[2025-07-11T16:00:12.186+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:  90%|######### | 36/40 [00:03<00:00, 15.27it/s]
[2025-07-11T16:00:12.187+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:  90%|######### | 36/40 [00:03<00:00, 11.35it/s]
[2025-07-11T16:00:12.702+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/ingestion_pipeline.py", line 68, in validate_data
    return _process_validation_results(result, filepath, total_rows)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ingestion_pipeline.py", line 112, in _process_validation_results
    condition = ~df[column].between(min_val, max_val, inclusive='both')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/series.py", line 5429, in between
    lmask = self >= left
            ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arraylike.py", line 60, in __ge__
    return self._cmp_method(other, operator.ge)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/series.py", line 5803, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 346, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 131, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '>=' not supported between instances of 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ingestion_pipeline.py", line 71, in validate_data
    raise AirflowFailException(f"Validation failed: {str(e)}")
airflow.exceptions.AirflowFailException: Validation failed: '>=' not supported between instances of 'str' and 'int'
[2025-07-11T16:00:12.716+0000] {taskinstance.py:1226} INFO - Immediate failure requested. Marking task as FAILED. dag_id=employee_ingestion_dag, task_id=validate_data, run_id=scheduled__2025-07-11T15:59:00+00:00, execution_date=20250711T155900, start_date=20250711T160005, end_date=20250711T160012
[2025-07-11T16:00:12.740+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-11T16:00:12.741+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 98 for task validate_data (Validation failed: '>=' not supported between instances of 'str' and 'int'; 644)
Traceback (most recent call last):
  File "/opt/airflow/dags/ingestion_pipeline.py", line 68, in validate_data
    return _process_validation_results(result, filepath, total_rows)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ingestion_pipeline.py", line 112, in _process_validation_results
    condition = ~df[column].between(min_val, max_val, inclusive='both')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/series.py", line 5429, in between
    lmask = self >= left
            ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arraylike.py", line 60, in __ge__
    return self._cmp_method(other, operator.ge)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/series.py", line 5803, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 346, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 131, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '>=' not supported between instances of 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ingestion_pipeline.py", line 71, in validate_data
    raise AirflowFailException(f"Validation failed: {str(e)}")
airflow.exceptions.AirflowFailException: Validation failed: '>=' not supported between instances of 'str' and 'int'
[2025-07-11T16:00:12.801+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-11T16:00:12.823+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-11T16:00:12.826+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
