[2025-07-11T15:55:02.380+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-11T15:55:02.406+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: employee_ingestion_dag.validate_data scheduled__2025-07-11T15:54:00+00:00 [queued]>
[2025-07-11T15:55:02.415+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: employee_ingestion_dag.validate_data scheduled__2025-07-11T15:54:00+00:00 [queued]>
[2025-07-11T15:55:02.416+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-11T15:55:02.428+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): validate_data> on 2025-07-11 15:54:00+00:00
[2025-07-11T15:55:02.438+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=472) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-11T15:55:02.440+0000] {standard_task_runner.py:72} INFO - Started process 473 to run task
[2025-07-11T15:55:02.441+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'employee_ingestion_dag', 'validate_data', 'scheduled__2025-07-11T15:54:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_pipeline.py', '--cfg-path', '/tmp/tmp2zyaoicg']
[2025-07-11T15:55:02.442+0000] {standard_task_runner.py:105} INFO - Job 83: Subtask validate_data
[2025-07-11T15:55:02.507+0000] {task_command.py:467} INFO - Running <TaskInstance: employee_ingestion_dag.validate_data scheduled__2025-07-11T15:54:00+00:00 [running]> on host 5a07e0ddeb4c
[2025-07-11T15:55:02.603+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='employee_ingestion_dag' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-11T15:54:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-11T15:54:00+00:00'
[2025-07-11T15:55:02.605+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-11T15:55:05.334+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/great_expectations/data_context/data_context/serializable_data_context.py:225: UserWarning: Warning. An existing `great_expectations.yml` was found here: /opt/airflow/gx.
    - No action was taken.
  warnings.warn(message)

[2025-07-11T15:55:05.336+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/great_expectations/data_context/data_context/serializable_data_context.py:233: UserWarning: Warning. An existing `config_variables.yml` was found here: /opt/airflow/gx/uncommitted.
    - No action was taken.
  warnings.warn(message)

[2025-07-11T15:55:05.371+0000] {file_data_context.py:222} INFO - FileDataContext loading fluent config
[2025-07-11T15:55:05.386+0000] {config.py:187} INFO - Loading 'datasources' ->
[{'assets': [...], 'name': 'employee_datasource', 'type': 'pandas'}]
[2025-07-11T15:55:05.387+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-11T15:55:05.554+0000] {abstract_data_context.py:5516} INFO - Loaded 'employee_datasource' from fluent config
[2025-07-11T15:55:05.594+0000] {file_data_context.py:174} INFO - Saving 1 Fluent Datasources to /opt/airflow/great_expectations/great_expectations.yml
[2025-07-11T15:55:05.595+0000] {fluent_base_model.py:276} INFO - PandasDatasource.dict() - missing `config_provider`, skipping config substitution
[2025-07-11T15:55:05.614+0000] {file_data_context.py:174} INFO - Saving 1 Fluent Datasources to /opt/airflow/great_expectations/great_expectations.yml
[2025-07-11T15:55:05.615+0000] {fluent_base_model.py:276} INFO - CSVAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-11T15:55:05.615+0000] {fluent_base_model.py:276} INFO - PandasDatasource.dict() - missing `config_provider`, skipping config substitution
[2025-07-11T15:55:05.680+0000] {validator.py:1461} INFO - 	14 expectation(s) included in expectation_suite.
[2025-07-11T15:55:06.278+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   0%|          | 0/40 [00:00<?, ?it/s]
[2025-07-11T15:55:06.280+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   0%|          | 0/40 [00:00<?, ?it/s]
[2025-07-11T15:55:06.281+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   5%|5         | 2/40 [00:00<00:00, 1233.44it/s]
[2025-07-11T15:55:06.640+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   5%|5         | 2/40 [00:00<00:06,  5.55it/s]  
[2025-07-11T15:55:06.641+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   5%|5         | 2/40 [00:00<00:06,  5.55it/s]
[2025-07-11T15:55:06.642+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   8%|7         | 3/40 [00:00<00:06,  5.55it/s]
[2025-07-11T15:55:06.953+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   8%|7         | 3/40 [00:00<00:08,  4.25it/s]
[2025-07-11T15:55:06.954+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   8%|7         | 3/40 [00:00<00:08,  4.25it/s]
[2025-07-11T15:55:07.274+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   8%|7         | 3/40 [00:00<00:08,  4.25it/s]
[2025-07-11T15:55:07.618+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   8%|7         | 3/40 [00:01<00:08,  4.25it/s]
[2025-07-11T15:55:07.934+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   8%|7         | 3/40 [00:01<00:08,  4.25it/s]
[2025-07-11T15:55:08.273+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   8%|7         | 3/40 [00:01<00:08,  4.25it/s]
[2025-07-11T15:55:08.604+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   8%|7         | 3/40 [00:02<00:08,  4.25it/s]
[2025-07-11T15:55:08.950+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:   8%|7         | 3/40 [00:02<00:08,  4.25it/s]
[2025-07-11T15:55:08.970+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:  38%|###7      | 15/40 [00:02<00:04,  5.67it/s]
[2025-07-11T15:55:08.970+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:  38%|###7      | 15/40 [00:02<00:04,  5.67it/s]
[2025-07-11T15:55:09.215+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:  38%|###7      | 15/40 [00:02<00:04,  5.67it/s]
[2025-07-11T15:55:09.243+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:  90%|######### | 36/40 [00:02<00:00, 15.59it/s]
[2025-07-11T15:55:09.244+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:  90%|######### | 36/40 [00:02<00:00, 15.59it/s]
[2025-07-11T15:55:11.741+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:  90%|######### | 36/40 [00:05<00:00, 15.59it/s]
[2025-07-11T15:55:11.743+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:  90%|######### | 36/40 [00:05<00:00, 15.59it/s]
[2025-07-11T15:55:11.743+0000] {logging_mixin.py:190} WARNING - Calculating Metrics:  90%|######### | 36/40 [00:05<00:00,  6.59it/s]
[2025-07-11T15:55:12.218+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/ingestion_pipeline.py", line 68, in validate_data
    return _process_validation_results(result, filepath, total_rows)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ingestion_pipeline.py", line 112, in _process_validation_results
    condition = ~df[column].between(min_val, max_val, inclusive='both')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/series.py", line 5429, in between
    lmask = self >= left
            ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arraylike.py", line 60, in __ge__
    return self._cmp_method(other, operator.ge)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/series.py", line 5803, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 346, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 131, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '>=' not supported between instances of 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ingestion_pipeline.py", line 71, in validate_data
    raise AirflowFailException(f"Validation failed: {str(e)}")
airflow.exceptions.AirflowFailException: Validation failed: '>=' not supported between instances of 'str' and 'int'
[2025-07-11T15:55:12.231+0000] {taskinstance.py:1226} INFO - Immediate failure requested. Marking task as FAILED. dag_id=employee_ingestion_dag, task_id=validate_data, run_id=scheduled__2025-07-11T15:54:00+00:00, execution_date=20250711T155400, start_date=20250711T155502, end_date=20250711T155512
[2025-07-11T15:55:12.255+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-11T15:55:12.256+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 83 for task validate_data (Validation failed: '>=' not supported between instances of 'str' and 'int'; 473)
Traceback (most recent call last):
  File "/opt/airflow/dags/ingestion_pipeline.py", line 68, in validate_data
    return _process_validation_results(result, filepath, total_rows)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ingestion_pipeline.py", line 112, in _process_validation_results
    condition = ~df[column].between(min_val, max_val, inclusive='both')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/series.py", line 5429, in between
    lmask = self >= left
            ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arraylike.py", line 60, in __ge__
    return self._cmp_method(other, operator.ge)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/series.py", line 5803, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 346, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 131, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '>=' not supported between instances of 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ingestion_pipeline.py", line 71, in validate_data
    raise AirflowFailException(f"Validation failed: {str(e)}")
airflow.exceptions.AirflowFailException: Validation failed: '>=' not supported between instances of 'str' and 'int'
[2025-07-11T15:55:12.311+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-11T15:55:12.332+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-11T15:55:12.336+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
